main/urls.py
# main/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('rotw/signup/', views.SignUp.as_view(), name='signup'),
]

rotw/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf.urls import url


from main.views import CheckUser, UserView, PlanView, ActivityView, RemoveActivityView, RemoveAvailabilityView, \
    AvailabilityView, PlanDetailsView, RemovePlanView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rotw/', include('main.urls')),
    path('rotw/', include('django.contrib.auth.urls')),
    path('rotw/home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('check/', CheckUser.as_view()),
    re_path(r'^rotw/(?P<id>(\d)+)$', UserView.as_view()),
    re_path(r'^rotw/(?P<u_id>(\d)+)/(?P<p_id>(\d)+)$', PlanView.as_view()),
    re_path(r'^rotw/activity/(?P<id>(\d)+)$', ActivityView.as_view()),
    re_path(r'^rotw/availability/(?P<id>(\d)+)$', AvailabilityView.as_view()),
    url(r'^rotw/plan/remove/(?P<pk>(\d)+)$', RemovePlanView.as_view()),
    url(r'^rotw/activity/remove/(?P<pk>(\d)+)$', RemoveActivityView.as_view()),
    url(r'^rotw/availability/remove/(?P<pk>(\d)+)$', RemoveAvailabilityView.as_view()),
    url(r'^rotw/schedule_details/(?P<u_id>(\d)+)/(?P<p_id>(\d)+)$', PlanDetailsView.as_view()),
    # url(r'^rotw/schedule_recalculation/(?P<u_id>(\d)+)/(?P<p_id>(\d)+)$', ScheduleRecalculation.as_view()),
]

main/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

COLORS = (          # todo przygotować paletę kolorów https://farbelous.io/bootstrap-colorpicker/
    (1, 'CadetBlue'),
    (2, 'Coral'),
    (3, 'CornFlowerBlue'),
    (4, 'Crimson'),
    (5, 'PaleVioletRed'),
    (6, 'LightBlue'),
    (7, 'DarkKhaki'),
    (8, 'DarkGoldenRod'),
    (9, 'LightSeaGreen'),
    (10, 'Olive'),
)


# TIME = [(i, datetime.timedelta(minutes=i*30)) for i in range(48)]
TIME = [(i, datetime.timedelta(minutes=i*30)) for i in range(14,45)]


class Plan(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('start_date', 'created', )


class Activities(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    description = models.CharField(max_length=255)
    priority = models.IntegerField()
    assumed_time = models.FloatField()
    applied_time = models.FloatField(default=0)
    color = models.IntegerField(choices=COLORS) # todo nadpisać str, żeby wyświetłały się nazwy kolorów

    class Meta:
        ordering = ('plan_id', '-priority', )


class Availability(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    day = models.IntegerField(default=1)
    start_time = models.IntegerField(choices=TIME) # todo ograniczenie co pół godziny
    end_time = models.IntegerField(choices=TIME) # todo ograniczenie co pół godziny
    duration = models.FloatField() # todo obliczenia w poście?, wartości zaokrąglone do połówek

    class Meta:
        ordering = ('plan_id', 'day','start_time', )


class Schedule(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    slot = models.ForeignKey(Availability, on_delete=models.CASCADE)
    start_time = models.IntegerField(choices=TIME)
    activity = models.ForeignKey(Activities, on_delete=models.CASCADE)
    order = models.IntegerField()
    duration = models.FloatField() # todo wartości zaokrąglone do połówek
    execution = models.FloatField(null=True)

templates/base.html
<!-- templates/base.html -->
{% load static %}
{% load mathfilters %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Allerta|Allura|Staatliches|Syncopate" rel="stylesheet">
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
    <main>
        <div class="center">
            <p style="vertical-align: center">
                <span class="header_schedule">schedule</span>
                <span class="header_rottweiler">rottweiler</span>
            </p>
            <p></p>
        </div>

    <ul>
        <li><a href='/rotw/home/'>Home</a></li>

        {%  if user.id != None %}
        <li>
            <a href='/rotw/{{ user.id }}'>My plans</a>
        </li>
        <li><a href="{% url 'logout' %}">Log out</a></li>
        {%  else %}
        <li><a href="{% url 'login' %}">Log in</a></li>
        <li><a href="{% url 'signup' %}">Register</a></li>
        {%  endif %}


    </ul>


        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

templates/edit_activity.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %} Activity details {% endblock %}

{% block content %}

<form method="post">
    {%  csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="send" name="submit">
</form>


{% endblock %}

templates/edit_availability.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %} Time slot details {% endblock %}

{% block content %}

<form method="post">
    {%  csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="send" name="submit">
</form>


{% endblock %}

templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <p class="center tom_xlarge"> Hi {{ user.username }}! </p>
    <p></p>
    <button class="center"> <a href="/rotw/{{ user.id }}"> check your schedules </a></button>
    <p></p>
    <button class="center back_tomato"><a href="{% url 'logout' %}">logout</a></button>
{% else %}
    <div class="center tom_xlarge">You are not logged in</div>
    <p></p>
    <button class="center"><a href="{% url 'login' %}">login</a></button>
    <p></p>
    <button  class="center"><a href="{% url 'signup' %}">register</a></button>
{% endif %}
{% endblock %}

templates/plan_view.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Plan details {% endblock %}

{% block content %}

<p class="regular"> <span class="tom_bold"> user: </span>{{ user.username }}</p>
<p class="regular"> <span class="tom_bold"> plan starting </span>{{ plan.start_date }}</p>

<p class="regular back_tomato">{{ m }}</p>

<div style="vertical-align: text-top">
    <div style="display: inline-block" class="regular">
        <p class="tom_xlarge"> activities included in the plan </p>

        <table class="table" style="width: 1000px">
            <tr class="table_header">
                <th> short name </th>
                <th> description </th>
                <th> priority </th>
                <th> hours (aspirational) </th>
                <th> displayed color </th>
                <th></th>
                <th></th>
            </tr>

        {% for a in plan_act %}
            <tr>
                <td> {{ a.name }} </td>
                <td> {{ a.description}} </td>
                <td> {{ a.priority}} </td>
                <td> {{ a.assumed_time}} </td>
                <td class="smaller_font"> {{ a.get_color_display }} </td>
                <td> <a href="/rotw/activity/{{ a.id }}"> edit </a> </td>
                <td> <a href="/rotw/activity/remove/{{ a.id }}"> delete </a> </td>

            </tr>
        {% endfor %}
        </table>
        <p class="table-danger"> initial time for all activities = {{ sum_act }} hours</p>
    </div>

    <div style="display: inline-block" class="regular">
        <p class="tom_xlarge"> add new activity </p>
        <form method="post">
                {%  csrf_token %}
                {{ form_act.as_p }}
                <input type="submit" value="add activity" name="submit" class="back_tomato">
        </form>

    </div>
</div>



<div>
    <div style="display:inline-block;" class="regular">
        <p class="tom_xlarge"> available time slots </p>
        <table class="table" style="width: 1000px">
            <tr  class="table_header">
                <th> day </th>
                <th> start time</th>
                <th> end time </th>
                <th> duration </th>
                <th></th>
                <th></th>
            </tr>

        {% for a in plan_ava %}
            <tr>
                <td> {{ a.day_label}} </td>
                <td> {{ a.get_start_time_display}} </td>
                <td> {{ a.get_end_time_display}} </td>
                <td> {{ a.duration|floatformat:1}} </td>
                <td> <a href="/rotw/availability/{{ a.id }}"> edit </a> </td>
                <td> <a href="/rotw/availability/remove/{{ a.id }}"> delete </a> </td>

            </tr>
        {% endfor %}
        </table>
        <p class="table-danger"> available time = {{ sum_ava }} hours</p>
    </div>

    <div style="display:inline-block" class="regular">
        <p class="tom_xlarge">add available time slot</p>
        <p class="smaller_font"> {{ first_day }} is day 1 of the plan </p>
        <form method="post">
        {%  csrf_token %}
        {{ form_ava.as_p }}

        <input type="submit" value="add time slot" name="submit" class="back_tomato">
        </form>

    </div>
</div>

<p></p>
<p>
    <a class="button center" href="/rotw/schedule_details/{{ user.id }}/{{ plan.id }}?val=true">
        <button class="button center back_cadetblue t_center f_white">
            calculate the schedule
        </button>
    </a>
</p>
<p></p>
<p>
    <a class="button center" href="/rotw/schedule_details/{{ user.id }}/{{ plan.id }}">
        <button class="button center back_grey t_center f_white">
            go to the schedule (without recalculation)
        </button>
    </a>
</p>


{#    <p class="regular"><a href="/rotw/schedule_recalculation/{{ user.id }}/{{ plan.id }}">recalculate the schedule</a></p>#}

{% endblock %}

templates/schedule.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load mathfilters %}
{% load timedelta_filter %}

{% block title %}Schedule details {% endblock %}

{% block content %}

<p class="container"> <span class="tom_bold">user: </span>{{ user.username }}</p>
<p class="container"> <span class="tom_bold">plan starting </span>{{ plan.start_date }}</p>

<h3 class="container tom_xlarge"> schedule </h3>

{% for day in graph %}
    <div class="container" style="font-size: 12x">{{ day.0.0 }}</div>
    <p></p>
    <div class="schedule container">
        {% for day, slot, activity, color in day %}
            <p class="schedule" style="background-color:{{ color }}">
                <span style="font-size: 11px">{{ slot }}</span> <br>{{ activity }}
            </p>

        {%  endfor %}
    </div>
    <p></p>
{% endfor %}

{#<p class=" regular"><a class="container" href="/rotw/schedule_details/{{ user.id }}/{{ plan.id }}?val=true">recalculate the schedule</a></p>#}
{#<p class=" regular"><a class="container" href="/rotw/{{ user.id }}/{{ plan.id }}"> go back to activities and time slots in this plan </a></p>#}
{#<p class=" regular"><a class="container" href="/rotw/{{ user.id }}"> go back to all my plans </a></p>#}

<p></p>
<p>
    <a class="button center" href="/rotw/schedule_details/{{ user.id }}/{{ plan.id }}?val=true">
        <button class="button center back_cadetblue t_center f_white">
            recalculate the schedule
        </button>
    </a>
</p>

<p></p>
<p>
    <a class="button center" href="/rotw/{{ user.id }}/{{ plan.id }}">
        <button class="button center back_grey t_center f_white">
            go back to activities and time slots in this plan
        </button>
    </a>
</p>

<p></p>
<p>
    <a class="button center" href="/rotw/{{ user.id }}">
        <button class="button center back_grey t_center f_white">
            go back to all of my plans
        </button>
    </a>
</p>




<p class="container tom_xlarge"> summary of time allocated to specific activities </p>
<table class="table container">
    <tr class="table_header">
        <th> id  </th>
        <th> name  </th>
        <th> description </th>
        <th> priority </th>
        <th> time (aspirational) </th>
        <th> time (applied) </th>
        <th> reduction (%) </th>

    </tr>

{% for a in activities %}
    <tr>
        <td> {{a.id}}</td>
        <td> {{a.name  }}</td>
        <td> {{a.description}} </td>
        <td> {{a.priority }}</td>
        <td> {{a.assumed_time }}</td>
        <td> {{a.applied_time }}</td>
        <td>
            {% with figure=a.applied_time|div:a.assumed_time|sub:1|mul:100 %}
            {{ figure|floatformat:"0" }}
            {% endwith %}%
        </td>
    </tr>
{% endfor %}
</table>

<p class="container tom_xlarge" > weekly schedule details</p>
<table class="table container">
    <tr class="table_header">
        <th> day  </th>
        <th> starting time  </th>
        <th> id  </th>
        <th> name  </th>
        <th> description </th>
        <th> priority </th>
    </tr>

{% for s in schedule %}
    <tr>
        <td> {{s.slot.day}}</td>
        <td> {{s.get_start_time_display}}</td>
        <td> {{s.activity.id}}</td>
        <td> {{s.activity.name  }}</td>
        <td> {{s.activity.description}} </td>
        <td> {{s.activity.priority }}</td>
    </tr>
{% endfor %}
</table>







{% endblock %}

templates/schedule_recalculation.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load mathfilters %}

{% block title %}Schedule recalculation{% endblock %}

{% block content %}

<p> summary of time allocated to specific activities </p>
<table>
    <tr>
        <th> id  </th>
        <th> name  </th>
        <th> description </th>
        <th> priority </th>
        <th> time (aspirational) </th>
        <th> time (applied) </th>
        <th> reduction (%) </th>

    </tr>

{% for a in activities %}
    <tr>
        <td> {{a.id}}</td>
        <td> {{a.name  }}</td>
        <td> {{a.description}} </td>
        <td> {{a.priority }}</td>
        <td> {{a.assumed_time }}</td>
        <td> {{a.applied_time }}</td>
        <td>
            {% with figure=a.applied_time|div:a.assumed_time|sub:1|mul:100 %}
            {{ figure|floatformat:"0" }}
            {% endwith %}%
        </td>
    </tr>
{% endfor %}
</table>

<p> weekly schedule </p>
<table>
    <tr>
        <th> day  </th>
        <th> starting time  </th>
        <th> id  </th>
        <th> name  </th>
        <th> description </th>
        <th> priority </th>
    </tr>

{% for s in schedule %}
    <tr>
        <td> {{s.slot.day}}</td>
        <td> {{s.get_start_time_display}}</td>
        <td> {{s.activity.id}}</td>
        <td> {{s.activity.name  }}</td>
        <td> {{s.activity.description}} </td>
        <td> {{s.activity.priority }}</td>
    </tr>
{% endfor %}
</table>

<p><a href="/rotw/schedule_details/{{ user.id }}/{{ plan.id }}">see the schedule</a></p>
<p><a href="/rotw/{{ user.id }}/{{ plan.id }}"> go back to activities and time slots in this plan </a></p>
<p><a href="/rotw/{{ user.id }}"> go back to all my plans </a></p>


{% endblock %}

templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <p class="center tom_xlarge">Sign up</p>
  <form method="post" class="center">
    {% csrf_token %}
    <table class="table info">
      {{ form }}
    </table>
        <button type="submit" class="center back_tomato">Sign up</button>
  </form>
{% endblock %}

templates/user_summary.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load mathfilters %}

{% block title %}Plans of {{ user.username }}{% endblock %}

{% block content %}
<p></p>
<p class="container tom_xlarge"> {{ user.username }}, these are your plans: </p>
<table class="container table">
    <tr class="table_header">
{#        <th> user id </th>#}
{#        <th> plan id </th>#}
        <th> plans' start date</th>
        <th> created </th>
        <th> status </th>
        <th></th>
        <th></th>
    </tr>

{% for p in plans %}
    <tr>

{#        <td> {{ p.user.id }}</td>#}
{#        <td> {{ p.id }}</td>#}
        <td> {{ p.start_date }}</td>
        <td class="smaller_font"> {{ p.created }}</td>


            {% if p.start_date > today  %}
                <td> not started yet </td>
            {% elif p.start_date < today_min6 %}
                <td class="back_grey">finished</td>
            {%  else %}
                <td class="back_tomato">on-going</td>
            {% endif %}


        <td> <a href="/rotw/{{ p.user.id }}/{{ p.id }}"> go to the plan </a> </td>
        <td> <a href="/rotw/plan/remove/{{ p.id }}"> delete </a> </td>
    </tr>
{% endfor %}
</table>

<p class="container tom_xlarge"> create a new plan </p>
<form method="post">
    <p class="container">
    {%  csrf_token %}
    {{ form }}
    <input type="submit" class="back_tomato" value="add">
    </p>
</form>

{% endblock %}

templates/users_list.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Users' list{% endblock %}

{% block content %}
<table>
    <th>
        <th> username</th>
        <th> last_login</th>
        <th> is_superuser</th>
        <th> first_name</th>
        <th> last_name</th>
        <th> email</th>
        <th> is_staff</th>
        <th> is_active</th>
        <th> date_joined</th>
        <th> password</th>
    </th>

{% for u in users %}
    <tr>
        <td> {{ u.id }}</td>
        <td> {{ u.username }}</td>
        <td> {{ u.last_login }}</td>
        <td> {{ u.is_superuser }}</td>
        <td> {{ u.first_name }}</td>
        <td> {{ u.last_name}}</td>
        <td> {{ u.email }}</td>
        <td> {{ u.is_staff }}</td>
        <td> {{ u.is_active }}</td>
        <td> {{ u.date_joined }}</td>
        <td> {{ u.password }}</td>
    </tr>
{% endfor %}
</table>
<h3> session:</h3>
<p> {{ session }}</p>
<h3> cookies:</h3>
<p> {{ cookies }}</p>
{% endblock %}